version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/toury_site
    ports:
      - "80:80"
      - "443:443"
  nodejs:
    image: node:11.14.0-alpine
    volumes:
      - ./:/var/www/toury_site
    working_dir: /var/www/toury_site
    tty: true